// Master registry of unique items (The "Book of Items")
const itemsCatalog = {
    "1mii-y8": { name: "1Mii Y8+", price: 60, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0DZHNWPKD%2Fref%3Dcm_sw_r_as_gl_api_gl_i_8N6015E1PEBPS034B4P8%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3D8803c8bc5823c050876f4707611b1a71&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/1Mii_Y8.jpg" },
    "7hz-x-crinacle-divine": { name: "7Hz x Crinacle: Divine", price: 150, url: "https://www.linsoul.com/products/7hz-x-crinacle-divine?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/7Hz_x_Crinacle_Divine.jpg" },
    "7hz-x-crinacle-zero-2": { name: "7hz x Crinacle Zero 2", price: 25, url: "https://www.linsoul.com/products/7hz-x-crinacle-zero-2?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/7HZ_x_Crinacle_Zero_2.jpg" },
    "anker-140w-max-4-port-gan-usb-c-charger": { name: "Anker 140W MAX 4-Port GaN USB C Charger", price: null, url: "https://amzn.to/4qBUvHq", pick: false, image: "images/Anker_140W_MAX_4-Port_GaN_USB_C_Charger.jpg" },
    "anker-555-usb-c-hub-8-in-1": { name: "Anker 555 USB-C Hub (8-in-1)", price: null, url: "https://amzn.to/4qGGrN6", pick: false, image: "images/Anker_555_USB-C_Hub_8-in-1.jpg" },
    "apos-x-community-gremlin-tube-amp": { name: "Apos x Community Gremlin Tube Amp", price: 120, url: "https://apos.audio/products/apos-x-community-gremlin-diy-tube-amp?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/Apos_x_Community_Gremlin_Tube_Amp.jpg" },
    "apos-x-community-rock-lobster-iems": { name: "Apos x Community Rock Lobster IEMs", price: 60, url: "https://apos.audio/products/apos-x-community-rock-lobster-iems?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/Apos_x_Community_Rock_Lobster_IEMs.jpg" },
    "audeze-lcd-3": { name: "Audeze LCD-3", price: 1950, url: "https://www.audeze.com/products/lcd-3?ar_clx=yes&ar_campaign=21899048795&ar_ad=720970113491&ar_adgroup=170863597872&ar_channel=google&gad_source=1&gad_campaignid=21899048795&gclid=Cj0KCQjwpv7NBhCzARIsADkIfWzyEqfL9JjexUQ5b0NaGKQwSllGZ-f5apqhCaO6OHELyp0UYIlw4McaAhoeEALw_wcB", pick: false, image: "images/Audeze_LCD-3.jpg" },
    "audeze-mm-500": { name: "Audeze MM-500", price: 1700, url: "https://amzn.to/40Pa83z", pick: false, image: "images/Audeze_MM-500.jpg" },
    "basn-bmaster5": { name: "BASN Bmaster5", price: 170, url: "https://amzn.to/4f9tXua", pick: false, image: "images/BASN_Bmaster5.jpg" },
    "bluetooth-hiby-w3-ii": { name: "Bluetooth HiBy W3 II", price: 49, url: "https://www.linsoul.com/products/hiby-w3-ii?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Bluetooth_HiBy_W3_II.png" },
    "bmedia-terras-cable": { name: "B_Media Terras Cable", price: 46, url: "https://www.linsoul.com/products/kiwi-ears-x-b_media-terras?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/B_Media_Terras_Cable.jpg" },
    "bose-qc-ultra-2": { name: "Bose QC Ultra 2", price: 450, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0FDKQ2FG6%2Fref%3Dcm_sw_r_as_gl_api_gl_i_KMZZ1JFZZ6GY3C88QWTP%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3D09ba8bbe979351a9c6fb08316894060e&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/Bose_QC_Ultra_2.jpg" },
    "but-constantly-on-sale-focal-hadenys": { name: "but constantly on sale Focal HADENYS", price: 750, url: "https://amzn.to/4lMy80L", pick: false, image: "images/but_constantly_on_sale_Focal_HADENYS.jpg" },
    "but-constantly-on-sale-sennheiser-hd-599": { name: "but constantly on sale Sennheiser HD 599", price: 240, url: "https://amzn.to/4bKO5QD", pick: false, image: "images/but_constantly_on_sale_Sennheiser_HD_599.jpg" },
    "cayin-n3ultra": { name: "Cayin N3Ultra", price: 530, url: "https://apos.audio/products/cayin-n3ultra-triple-timbre-digital-audio-player?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/Cayin_N3Ultra.jpg" },
    "cmf-buds-pro-2": { name: "CMF Buds Pro 2", price: 60, url: "https://amzn.to/45m8kku", pick: false, image: "images/CMF_Buds_Pro_2.png" },
    "cmf-by-nothing-headphone-pro": { name: "CMF by Nothing Headphone Pro", price: 100, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0FKG6TDRR%2Fref%3Dcm_sw_r_as_gl_api_gl_i_10TV6G03W2PC25HEMKE4%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3D8cc5f836f5310ef8f0690b0d272abf92&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/CMF_by_Nothing_Headphone_Pro.jpg" },
    "crinear-daybreak": { name: "Crinear Daybreak", price: 170, url: "https://www.linsoul.com/products/crinear-daybreak?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Crinear_Daybreak.jpg" },
    "crinear-protocol-max": { name: "CrinEar Protocol Max", price: 90, url: "https://www.linsoul.com/products/crinear-protocol-max?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/CrinEar_Protocol_Max.jpg" },
    "crinear-reference": { name: "CrinEar Reference", price: 350, url: "https://www.linsoul.com/products/crinear-reference?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/CrinEar_Reference.jpg" },
    "da-alpha": { name: "D&A Alpha", price: 400, url: "https://shenzhenaudio.com/products/d-a-alpha-dual-es9039q2m-desktop-dac-headphone-amplifier", pick: true, image: "images/DA_Alpha.jpg" },
    "dji-osmo-pocket-3-creator-combo": { name: "DJI Osmo Pocket 3 Creator Combo", price: null, url: "https://amzn.to/4ehvFtn", pick: false, image: "images/DJI_Osmo_Pocket_3_Creator_Combo.jpg" },
    "dunu-mortise": { name: "DUNU Mortise", price: 430, url: "https://www.linsoul.com/products/dunu-mortise?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/DUNU_Mortise.jpg" },
    "edifier-wh950nb-gen-2": { name: "Edifier WH950NB Gen 2", price: 200, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0F9DR3ZPG%2Fref%3Dcm_sw_r_as_gl_api_gl_i_GB8KPT5H212NJDBAW7FR%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3Dea64e230ceca064790cccc11d02a9ecb&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/Edifier_WH950NB_Gen_2.jpg" },
    "fatfreq-maestro-se-universals": { name: "FatFreq Maestro SE Universals", price: 2500, url: "https://fatfreq.com/products/maestro-se?srsltid=AfmBOoppbPC40665jKDzhpH6lchKDLBP_Stg5txzJAnnbUgeKlVoit-q", pick: false, image: "images/FatFreq_Maestro_SE_Universals.jpg" },
    "fiio-eh11": { name: "FiiO EH11", price: 35, url: "https://www.linsoul.com/products/fiio-eh11?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/FiiO_EH11.jpg" },
    "fiio-eh13": { name: "FiiO EH13", price: 60, url: "https://www.linsoul.com/products/fiio-eh13?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/FiiO_EH13.jpg" },
    "fiio-ft1": { name: "FiiO FT1", price: 160, url: "https://www.linsoul.com/products/fiio-ft1?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/FiiO_FT1.png" },
    "fiio-ft1-pro": { name: "FiiO FT1 Pro", price: 220, url: "https://apos.audio/products/fiio-ft1-pro-open-back?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/FiiO_FT1_Pro.jpg" },
    "fiio-ft7": { name: "FiiO FT7", price: 700, url: "https://apos.audio/products/fiio-ft7-planar-magnetic-open-back-headphones?sca_ref=9857353.lTWqXMxzNa", pick: true, image: "images/FiiO_FT7.jpg" },
    "fiio-jade-audio-jt3": { name: "FiiO JadeAudio JT7", price: 120, url: "https://apos.audio/products/fiio-jadeaudio-jt7-open-back-planar-headphones?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/FiiO_Jade_Audio_JT3.jpg" },
    "fiio-k11": { name: "FiiO K11", price: 140, url: "https://www.linsoul.com/products/fiio-k11?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/FiiO_K11.jpg" },
    "fiio-ka15": { name: "FiiO KA15", price: 95, url: "https://www.linsoul.com/products/fiio-ka15?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/FiiO_KA15.png" },
    "fiio-m21": { name: "FiiO M21", price: 330, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0F8HVKTB9%2Fref%3Dcm_sw_r_as_gl_api_gl_i_3AE8XXTMSQ46W1HFYXMR%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3Dabcb6e8f945a52f32b302ca17fd8eb8c&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/FiiO_M21.jpg" },
    "fiio-m23": { name: "FiiO M23", price: 720, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0D14PGZV1%2Fref%3Dcm_sw_r_as_gl_api_gl_i_TK9CDFZVGYHMD8H3WVQX%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3D98aa5a3055150f1c4be2bcfc78367188&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/FiiO_M23.jpg" },
    "fiio-oak-nano": { name: "FIIO OAK NANO", price: 490, url: "https://www.linsoul.com/products/fiio-oak-nano?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/FIIO_OAK_NANO.jpg" },
    "fiio-snowsky-echo-mini": { name: "FiiO SNOWSKY Echo Mini", price: 55, url: "https://www.linsoul.com/products/fiio-snowsky-echo-mini?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/FiiO_SNOWSKY_Echo_Mini.jpg" },
    "focal-azurys": { name: "Focal Azurys", price: 600, url: "https://amzn.to/4evNOSA", pick: false, image: "images/Focal_Azurys.png" },
    "focal-hadenys": { name: "Focal Hadenys", price: 750, url: "https://amzn.to/4oxjjj6", pick: true, image: "images/Focal_Hadenys.png" },
    "fosi-audio-ds3": { name: "Fosi Audio MD3", price: 150, url: "https://fosiaudioshop.com/products/fosi-audio-md3-magdac-portable-dac-headphone-amplifier-with-rear-display?sca_ref=9795660.evSmNtMEvd&utm_source=affiliate&utm_medium=referral&utm_campaign=uppromote", pick: false, image: "images/Fosi_Audio_DS3.jpg" },
    "fosi-audio-i5": { name: "Fosi Audio i5", price: 550, url: "https://fosiaudioshop.com/products/i5-headphones?sca_ref=9795660.evSmNtMEvd&utm_source=affiliate&utm_medium=referral&utm_campaign=uppromote", pick: true, image: "images/Fosi_Audio_i5.jpg" },
    "fosi-audio-im4": { name: "Fosi Audio IM4", price: 100, url: "https://fosiaudioshop.com/products/fosi-audio-im4?sca_ref=9795660.evSmNtMEvd&utm_source=affiliate&utm_medium=referral&utm_campaign=uppromote", pick: true, image: "images/Fosi_Audio_IM4.jpg" },
    "fosi-audio-k7": { name: "Fosi Audio K7", price: 200, url: "https://fosiaudioshop.com/products/k7-dac-headphone-amp?sca_ref=9795660.evSmNtMEvd&utm_source=affiliate&utm_medium=referral&utm_campaign=uppromote", pick: false, image: "images/Fosi_Audio_K7.jpg" },
    "fosi-audio-zh3": { name: "Fosi Audio ZH3", price: 200, url: "https://fosiaudioshop.com/products/zh3-dac-headphone-amp-preamp?sca_ref=9795660.evSmNtMEvd&utm_source=affiliate&utm_medium=referral&utm_campaign=uppromote", pick: true, image: "images/Fosi_Audio_ZH3.jpg" },
    "gaming-audeze-maxwell-2": { name: "Gaming Audeze Maxwell 2", price: 330, url: "https://apos.audio/products/audeze-maxwell-2-wireless-gaming-headset?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/Gaming_Audeze_Maxwell_2.png" },
    "harmonicdyne-romantic": { name: "Harmonicdyne Romantic", price: 340, url: "https://www.linsoul.com/products/harmonicdyne-romantic?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Harmonicdyne_Romantic.jpg" },
    "hart-audio": { name: "Hart Audio", price: null, url: "https://hartaudiocables.com/?srsltid=AfmBOorgjh48BSZb8D_oMEq1M8iBLxZtShzNSawmyPz1jcFDVez2CGKQ", pick: false, image: "images/Hart_Audio.jpg" },
    "headset-drop-pc38x": { name: "Headset DROP PC38X", price: 200, url: "https://amzn.to/3HhZLiJ", pick: false, image: "images/Headset_DROP_PC38X.png" },
    "hiby-r1": { name: "HiBy R1", price: 85, url: "https://www.linsoul.com/products/hiby-r1?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/HiBy_R1.jpg" },
    "hiby-r4": { name: "HiBy R4", price: 250, url: "https://www.linsoul.com/products/hiby-r4?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/HiBy_R4.jpg" },
    "hiby-r6-iii": { name: "Hiby R6 III", price: 440, url: "https://www.linsoul.com/products/hiby-r6-iii-2025?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Hiby_R6_III.jpg" },
    "hidizs-mp145-pro": { name: "Hidizs MP145 PRO", price: 190, url: "https://www.linsoul.com/products/hidizs-mp145-pro?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Hidizs_MP145_PRO.jpg" },
    "hidizs-x-linsoul-ap80-pro-max": { name: "HIDIZS x Linsoul AP80 PRO MAX", price: 190, url: "https://www.linsoul.com/products/hidizs-x-linsoul-ap80pro-max?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/HIDIZS_x_Linsoul_AP80_PRO_MAX.jpg" },
    "hifiman-sundara": { name: "Hifiman Sundara", price: 280, url: "https://apos.audio/products/hifiman-sundara-planar-magnetic-headphones?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/Hifiman_Sundara.png" },
    "ifi-uno": { name: "IFI Uno", price: 79, url: "https://apos.audio/products/ifi-uno?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/IFI_Uno.png" },
    "inawaken-dawn-mistwood": { name: "INAWAKEN Dawn Mistwood", price: 70, url: "https://www.linsoul.com/products/inawaken-dawn-mistwood?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/INAWAKEN_Dawn_Mistwood.jpg" },
    "inawaken-dawn-ms": { name: "INAWAKEN DAWN Ms", price: 50, url: "https://www.linsoul.com/products/inawaken-dawn-ms?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/INAWAKEN_DAWN_Ms.jpg" },
    "inawaken-twilight-ds": { name: "INAWAKEN Twilight-DS", price: 350, url: "https://www.linsoul.com/products/inawaken-twilight-ds?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/INAWAKEN_Twilight-DS.jpg" },
    "ioaudio-cielo": { name: "IOAUDIO CIELO", price: 1000, url: "https://shenzhenaudio.com/collections/headphones/products/ioaudio-cielo-16-balanced-armatures-in-ear-headphone?_fid=eebacd484&_pos=23&_ss=c&ref=tsmeyyjl&utm_source=affiliate", pick: true, image: "images/IOAUDIO_CIELO.jpg" },
    "jcally-jm6-pro": { name: "JCALLY JM6 Pro", price: 18, url: "https://amzn.to/3TMeGUZ", pick: false, image: "images/JCALLY_JM6_Pro.png" },
    "juzear-x-z-reviews-defiant": { name: "JUZEAR x Z Reviews Defiant", price: 90, url: "https://hifigo.com/products/juzear-x-z-reviews-defiant?rfsn=8882848.207d9c&variant=46359559897327", pick: false, image: "images/JUZEAR_x_Z_Reviews_Defiant.jpg" },
    "kefine-delci": { name: "Kefine Delci", price: 75, url: "https://www.linsoul.com/products/kefine-delci?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kefine_Delci.jpg" },
    "kefine-klean": { name: "Kefine Klean", price: 50, url: "https://www.linsoul.com/products/kefine-klean?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kefine_Klean.png" },
    "keychron-m6-8k-wireless-gaming-mouse": { name: "Keychron M6 8K Wireless Gaming Mouse", price: null, url: "https://amzn.to/4sjqEEb", pick: false, image: "images/Keychron_M6_8K_Wireless_Gaming_Mouse.jpg" },
    "keychron-q1-ultra-8k-75-wireless-mechanical-keyboard": { name: "Keychron Q1 Ultra 8K 75% Wireless Mechanical Keyboard", price: null, url: "https://amzn.to/4mba2Nk", pick: false, image: "images/Keychron_Q1_Ultra_8K_75_Wireless_Mechanical_Keyboard.jpg" },
    "kf-concept-60-inch-carbon-fiber-camera-tripodsuper-lightweight-compact-travel-tripod-with-360-degree-ball-headquick-release-platedetachable-monopod-17-lb-load-capacity-for-slr-dslr-c225c0-ba225": { name: "K&F Concept 60 inch Carbon Fiber Camera Tripod,Super Lightweight Compact Travel Tripod with 360 Degree Ball Head,Quick Release Plate,Detachable Monopod 17 lb Load Capacity for SLR DSLR C225C0 (BA225)", price: null, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB081DYTR9J%2Fref%3Dcm_sw_r_as_gl_api_gl_i_8M5S06Y5VWKNQEJ8C92X%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3Dd987bf5298e45df9bfdb78f767025db2&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/KF_Concept_60_inch_Carbon_Fiber_Camera_TripodSuper_Lightweight_Compact_Travel_Tripod_with_360_Degree_Ball_HeadQuick_Release_PlateDetachable_Monopod_17_lb_Load_Capacity_for_SLR_DSLR_C225C0_BA225.jpg" },
    "kf-concept-67mm-variable-fader-nd2-32-nd-filter-and-cpl-circular-polarizing-lens-filter-in-1-for-camera-lens-waterproof-neutral-density-polarizer-filter-nano-d-series": { name: "K&F CONCEPT 67mm Variable Fader ND2-32 ND Filter and CPL Circular Polarizing Lens Filter in 1 for Camera Lens Waterproof Neutral Density Polarizer Filter (Nano-D Series)", price: null, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0CNV9W4V4%2Fref%3Dcm_sw_r_as_gl_api_gl_i_dl_BAV07S149SNKBK84W03Z%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3D7c705aee77f7273683cd5d0d4d8feadb&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/KF_CONCEPT_67mm_Variable_Fader_ND2-32_ND_Filter_and_CPL_Circular_Polarizing_Lens_Filter_in_1_for_Camera_Lens_Waterproof_Neutral_Density_Polarizer_Filter_Nano-D_Series.jpg" },
    "kickstarter-thieaudio-cypher": { name: "Kickstarter THIEAUDIO Cypher", price: null, url: "https://www.linsoul.com/products/thieaudio-cypher?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kickstarter_THIEAUDIO_Cypher.jpg" },
    "kiwi-ears-ad1": { name: "Kiwi Ears AD1", price: 10, url: "https://www.linsoul.com/products/kiwi-ears-ad1?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_AD1.jpg" },
    "kiwi-ears-allegro-mini": { name: "Kiwi Ears Allegro Mini", price: 25, url: "https://www.linsoul.com/products/kiwi-ears-allegro-mini?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_Allegro_Mini.jpg" },
    "kiwi-ears-allegro-pro": { name: "Kiwi Ears Allegro Pro", price: 60, url: "https://www.linsoul.com/products/kiwi-ears-allegro-pro?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_Allegro_Pro.jpg" },
    "kiwi-ears-altruva": { name: "Kiwi Ears Altruva", price: 70, url: "https://www.linsoul.com/products/kiwi-ears-altruva?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_Altruva.jpg" },
    "kiwi-ears-astral": { name: "Kiwi Ears Astral", price: 300, url: "https://www.linsoul.com/products/kiwi-ears-astral?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_Astral.jpg" },
    "kiwi-ears-belle": { name: "Kiwi Ears Belle", price: 30, url: "https://www.linsoul.com/products/kiwi-ears-belle?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_Belle.jpg" },
    "kiwi-ears-cadenza-ii": { name: "Kiwi Ears Cadenza II", price: 50, url: "https://www.linsoul.com/products/kiwi-ears-cadenza-ii?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_Cadenza_II.jpg" },
    "kiwi-ears-halcyon": { name: "Kiwi Ears Halcyon", price: 260, url: "https://www.linsoul.com/products/kiwi-ears-halcyon?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_Halcyon.jpg" },
    "kiwi-ears-septet": { name: "Kiwi Ears Septet", price: 270, url: "https://www.linsoul.com/products/kiwi-ears-septet?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_Septet.jpg" },
    "kiwi-ears-tude": { name: "Kiwi Ears Étude", price: 120, url: "https://www.linsoul.com/products/kiwi-ears-etude?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_Étude.jpg" },
    "kiwi-ears-x-bmedia-chorus": { name: "Kiwi Ears x B_Media Chorus", price: 40, url: "https://www.linsoul.com/products/kiwi-ears-x-b_media-chorus?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/Kiwi_Ears_x_B_Media_Chorus.jpg" },
    "kiwi-ears-x-bmedia-terras": { name: "Kiwi Ears x B_Media: Terras", price: null, url: "https://www.linsoul.com/products/kiwi-ears-x-b_media-terras?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/Kiwi_Ears_x_B_Media_Terras.jpg" },
    "kiwi-ears-x-hbb-punch": { name: "Kiwi Ears x HBB Punch", price: 450, url: "https://www.linsoul.com/products/kiwi-ears-x-hbb-punch?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_x_HBB_Punch.jpg" },
    "letshuoer-astralis": { name: "LETSHUOER Astralis", price: 180, url: "https://letshuoer.net/products/letshuoer-astralis-hifi-in-ear-earphones-15-5mm-5th-generation-planar-diaphragm-driver?sca_ref=9494666.Bbv8z0WcOh", pick: true, image: "images/LETSHUOER_Astralis.jpg" },
    "letshuoer-ember": { name: "LETSHUOER Ember", price: 500, url: "https://letshuoer.net/products/letshuoer-ember-14-8mm-large-flagship-planar-magnetic-hi-fi-in-ear-monitors?sca_ref=9494666.Bbv8z0WcOh", pick: false, image: "images/LETSHUOER_Ember.jpg" },
    "letshuoer-lc01-usb-type-c": { name: "LETSHUOER LC01 USB Type-C", price: null, url: "https://letshuoer.net/products/letshuoer-lc01-usb-type-c-earphones-cable?sca_ref=9494666.Bbv8z0WcOh", pick: false, image: "images/LETSHUOER_LC01_USB_Type-C.jpg" },
    "letshuoer-mystic-8": { name: "LETSHUOER Mystic 8", price: 990, url: "https://letshuoer.net/products/letshuoer-mystic-8-wired-iem-hifi-earphones-8-ba-drivers-in-ear-monitor?sca_ref=9494666.Bbv8z0WcOh", pick: false, image: "images/LETSHUOER_Mystic_8.jpg" },
    "meze-109-pro": { name: "Meze 109 Pro", price: 800, url: "https://apos.audio/products/meze-audio-109-pro?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/Meze_109_Pro.png" },
    "mic-moondrop-mc1": { name: "Mic Moondrop MC1", price: null, url: "https://www.linsoul.com/products/moondrop-mc1?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Mic_Moondrop_MC1.jpg" },
    "moondrop-dawn-pro-2": { name: "Moondrop Dawn Pro 2", price: 60, url: "https://www.linsoul.com/products/moondrop-dawn-pro2?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Moondrop_Dawn_Pro_2.jpg" },
    "moondrop-edge": { name: "Moondrop Edge", price: 90, url: "https://www.linsoul.com/products/moondrop-edge?_pos=10&_sid=2605a58ec&_ss=r&sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Moondrop_Edge.jpg" },
    "moondrop-golden-ages-2": { name: "Moondrop Golden Ages 2", price: 90, url: "https://shenzhenaudio.com/products/moondrop-golden-ages-2-13mm-planar-true-wireless-headphone-tws?ref=tsmeyyjl&utm_source=affiliate", pick: false, image: "images/Moondrop_Golden_Ages_2.png" },
    "moondrop-lan-ii": { name: "Moondrop LAN II", price: 60, url: "https://www.linsoul.com/products/moondrop-lanii?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Moondrop_LAN_II.jpg" },
    "moondrop-moonriver-3": { name: "Moondrop Moonriver 3", price: 220, url: "https://apos.audio/products/moondrop-moonriver-3-flagship-mini-portable-dac-amp?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/Moondrop_Moonriver_3.jpg" },
    "moondrop-old-fashioned": { name: "MOONDROP Old Fashioned", price: 25, url: "https://www.linsoul.com/products/moondrop-old-fashioned?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/MOONDROP_Old_Fashioned.jpg" },
    "moondrop-pudding": { name: "MOONDROP Pudding", price: 50, url: "https://shenzhenaudio.com/products/moondrop-pudding-true-wireless-headphone-tws?variant=49100163350771", pick: true, image: "images/MOONDROP_Pudding.jpg" },
    "moondrop-rays": { name: "MOONDROP RAYS", price: 100, url: "https://www.linsoul.com/products/moondrop-rays?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/MOONDROP_RAYS.jpg" },
    "moondrop-robin": { name: "Moondrop Robin", price: 90, url: "https://shenzhenaudio.com/products/moondrop-robins-earphones-true-wireless-headphone-tws?variant=46516174881011", pick: true, image: "images/Moondrop_Robin.png" },
    "moondrop-skyland": { name: "Moondrop Skyland", price: 800, url: "https://apos.audio/products/moondrop-skyland-full-size-planar-magnetic-headphone?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/Moondrop_Skyland.jpg" },
    "moondrop-space-travel-2": { name: "Moondrop Space Travel 2", price: 30, url: "https://www.linsoul.com/products/moondrop-space-travel-2?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/Moondrop_Space_Travel_2.jpg" },
    "moondrop-x-smsl-dha15": { name: "Moondrop x SMSL DHA15", price: 650, url: "https://apos.audio/products/moondrop-dha15-all-in-one-dac-amp?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/Moondrop_x_SMSL_DHA15.jpg" },
    "nicehck-08-silicone-ear-tips-noise-isolating": { name: "NICEHCK 08 Silicone Ear Tips Noise Isolating", price: null, url: "https://nicehck.com/products/nicehck-08-silicone-ear-tips-noise-isolating-earbuds-cushion-earphone-accessories-improve-clear-vocal-for-nx7mk4-zero-2-t2-gk20?sca_ref=9185017.bnGYqsxONg", pick: false, image: "images/NICEHCK_08_Silicone_Ear_Tips_Noise_Isolating.jpg" },
    "nicehck-blackwheat-iem-wmic": { name: "NICEHCK BlackWheat IEM w/mic", price: null, url: "https://nicehck.com/products/nicehck-blackwheat-8-core-silver-plated-copper-microphone-cable-mmcx-qdc-0-78-2pin-for-db3-zsn-zst-as10-zs10-edx-c10-ca4-c12?variant=47860952662307&sca_ref=9185017.bnGYqsxONg", pick: false, image: "images/NICEHCK_BlackWheat_IEM_wmic.jpg" },
    "nicehck-c04-liquid-silicone-eartips": { name: "NICEHCK C04 Liquid Silicone Eartips", price: null, url: "https://nicehck.com/products/nicehck-c04-liquid-silicone-ear-tips?sca_ref=9185017.bnGYqsxONg", pick: true, image: "images/NICEHCK_C04_Liquid_Silicone_Eartips.jpg" },
    "nicehck-nk1-max": { name: "NICEHCK NK1 MAX", price: 24, url: "https://nicehck.com/products/nicehck-nki-max-portable-dac-adapter-cable?sca_ref=9185017.bnGYqsxONg", pick: true, image: "images/NICEHCK_NK1_MAX.jpg" },
    "nicehck-nx8": { name: "NICEHCK NX8", price: 200, url: "https://nicehck.com/products/nicehck-nx8-in-ear-monitor-with-1dd-6ba-1pzt-8-unit-hybrid-earphone?sca_ref=9185017.bnGYqsxONg", pick: false, image: "images/NICEHCK_NX8.png" },
    "nicehck-nx8-se": { name: "NICEHCK NX8 SE", price: 250, url: "https://nicehck.com/products/nicehck-nx8-se-nx8-special-edition-iems?sca_ref=9185017.bnGYqsxONg", pick: true, image: "images/NICEHCK_NX8_SE.jpg" },
    "nicehck-nx8ti-limited-edition": { name: "NICEHCK NX8Ti Limited Edition", price: 400, url: "https://nicehck.com/products/nicehck-hifi-iem-nx8ti-limited-edition?sca_ref=9185017.bnGYqsxONg", pick: false, image: "images/NICEHCK_NX8Ti_Limited_Edition.jpg" },
    "nicehck-octave": { name: "NICEHCK Octave", price: 80, url: "https://nicehck.com/products/nicehck-octave-es9039q2m-flagship-portable-dac?sca_ref=9185017.bnGYqsxONg", pick: false, image: "images/NICEHCK_Octave.jpg" },
    "nicehck-tears": { name: "NICEHCK Tears", price: 30, url: "https://nicehck.com/products/tears?sca_ref=9185017.bnGYqsxONg", pick: false, image: "images/NICEHCK_Tears.jpg" },
    "nothing-headphone-a": { name: "Nothing Headphone (a)", price: 200, url: "https://amzn.to/40yEkQs", pick: false, image: "images/Nothing_Headphone_a.jpg" },
    "ooopusx-op22": { name: "ooopusX Op.22", price: 35, url: "https://shenzhenaudio.com/collections/new-arrivals/products/ooopusx-op-22-2dd-2ba-in-ear-headphone?ref=tsmeyyjl&utm_source=affiliate", pick: true, image: "images/ooopusX_Op22.jpg" },
    "original-kiwi-ears-terras": { name: "Original Kiwi Ears Terras", price: null, url: "https://www.linsoul.com/products/kiwi-ears-terras?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Original_Kiwi_Ears_Terras.jpg" },
    "punch-audio-martilo": { name: "Punch Audio Martilo", price: 330, url: "https://www.linsoul.com/products/punch-audio-martilo?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Punch_Audio_Martilo.png" },
    "questyle-m15i": { name: "Questyle M15i", price: 250, url: "https://amzn.to/4evROCA", pick: false, image: "images/Questyle_M15i.png" },
    "questyle-sigma": { name: "Questyle Sigma", price: 600, url: "https://amzn.to/3Npc92M", pick: false, image: "images/Questyle_Sigma.jpg" },
    "rog-x-hifiman-kithara": { name: "ROG x Hifiman Kithara", price: 300, url: "https://amzn.to/4awEqfZ", pick: true, image: "images/ROG_x_Hifiman_Kithara.jpg" },
    "salad-halo-headphone-stand": { name: "Salad Halo Headphone Stand", price: null, url: "https://apos.audio/products/salad-halo-headphone-stand?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/Salad_Halo_Headphone_Stand.jpg" },
    "schiit-fulla": { name: "Schiit Fulla", price: 136, url: "https://amzn.to/403r0nk", pick: false, image: "images/Schiit_Fulla.png" },
    "schiit-gunnr-mission-critical": { name: "Schiit Gunnr Mission-Critical", price: 259, url: "https://amzn.to/3TsPAKC", pick: false, image: "images/Schiit_Gunnr_Mission-Critical.png" },
    "sennheiser-hd-560-s": { name: "Sennheiser HD 560 S", price: 275, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB08J9MVB6W%2Fref%3Dcm_sw_r_as_gl_api_gl_i_GHA0516AARS5E63DD09E%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3Dcb1741c88340e67df6d3d142d6253491&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/Sennheiser_HD_560_S.jpg" },
    "sennheiser-hd599": { name: "Sennheiser HD599", price: 200, url: "https://amzn.to/4nl2vvE", pick: true, image: "images/Sennheiser_HD599.png" },
    "sennheiser-hd620s": { name: "Sennheiser HD620S", price: 400, url: "https://amzn.to/4eytz6T", pick: false, image: "images/Sennheiser_HD620S.png" },
    "sennheiser-hdb-630": { name: "Sennheiser HDB 630", price: 500, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0FK4K5Z37%2Fref%3Dcm_sw_r_as_gl_api_gl_i_J5QCFF41K3X5F978M3Z1%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3Ddc35d45f37440632ee3611e6c7b1fbdd&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/Sennheiser_HDB_630.jpg" },
    "sennheiser-mke-400-mobile-kit": { name: "SENNHEISER MKE 400 + Mobile Kit", price: null, url: "https://amzn.to/4qx1hPm", pick: false, image: "images/SENNHEISER_MKE_400__Mobile_Kit.jpg" },
    "shanling-m0-pro": { name: "SHANLING M0 Pura", price: 140, url: "https://amzn.to/4njSsHM", pick: false, image: "images/SHANLING_M0_Pro.jpg" },
    "shanling-m0s": { name: "SHANLING M0s", price: 100, url: "https://amzn.to/4nc3D54", pick: false, image: "images/SHANLING_M0s.jpg" },
    "shanling-m1-plus": { name: "Shanling M3 Plus", price: 469, url: "https://www.linsoul.com/products/shanling-m3-plus?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Shanling_M1_Plus.jpg" },
    "shanling-m7t": { name: "Shanling M7T", price: 1200, url: "https://www.linsoul.com/products/shanling-m7t?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Shanling_M7T.jpg" },
    "shanling-ua7-its-got-a-tube": { name: "Shanling UA7 ITS GOT A TUBE", price: 270, url: "https://www.linsoul.com/products/shanling-ua7?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/Shanling_UA7_ITS_GOT_A_TUBE.jpg" },
    "simgot-em6l": { name: "SIMGOT EM6L", price: 125, url: "https://www.linsoul.com/products/simgot-em6l?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/SIMGOT_EM6L.jpg" },
    "simgot-ep5": { name: "Simgot EP5", price: 98, url: "https://www.linsoul.com/products/simgot-ep5?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Simgot_EP5.png" },
    "simgot-ew300": { name: "SIMGOT EW300", price: 80, url: "https://www.linsoul.com/products/simgot-ew300?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/SIMGOT_EW300.jpg" },
    "sivga-peng": { name: "SIVGA Peng", price: 500, url: "https://www.linsoul.com/products/sivga-peng?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/SIVGA_Peng.jpg" },
    "sony-alpha-a6400-mirrorless-camera-compact-aps-c-interchangeable-lens-digital-camera-with-real-time-eye-auto-focus-4k-video-flip-up-touchscreen-e-mount-compatible-cameras-ilce-6400b-body": { name: "Sony Alpha a6400 Mirrorless Camera: Compact APS-C Interchangeable Lens Digital Camera with Real-Time Eye Auto Focus, 4K Video & Flip Up Touchscreen - E Mount Compatible Cameras - ILCE-6400/B Body", price: null, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB07MTWVN3M%2Fref%3Dcm_sw_r_as_gl_api_gl_i_FNG9TMGEJ2YYAD1EY767%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3D226d9c09123e826a0039edad56cfc99c&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/Sony_Alpha_a6400_Mirrorless_Camera_Compact_APS-C_Interchangeable_Lens_Digital_Camera_with_Real-Time_Eye_Auto_Focus_4K_Video__Flip_Up_Touchscreen_-_E_Mount_Compatible_Cameras_-_ILCE-6400B_Body.jpg" },
    "sony-inzone-h6-air": { name: "Sony INZONE H6 Air", price: 200, url: "https://amzn.to/4nNAXzP", pick: false, image: "images/Sony_INZONE_H6_Air.jpg" },
    "soundpeats-air5-pro": { name: "Soundpeats Air5 Pro+", price: 130, url: "https://amzn.to/4aByvYz", pick: false, image: "images/Soundpeats_Air5_Pro.jpg" },
    "soundpeats-clip1": { name: "SoundPEATS Clip1", price: 70, url: "https://amzn.to/47Z9zrG", pick: false, image: "images/SoundPEATS_Clip1.jpg" },
    "soundpeats-clip1-open-ear-earbuds": { name: "SoundPEATS Clip1 Open Ear Earbuds", price: 70, url: "https://amzn.to/4sqNgnA", pick: false, image: "images/SoundPEATS_Clip1_Open_Ear_Earbuds.jpg" },
    "soundpeats-h3": { name: "SoundPEATS H3", price: 130, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0FJKYVSMP%2Fref%3Dcm_sw_r_as_gl_api_gl_i_RXTZ92A5JQYJFTP9PNMW%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3D60a065112fb14a8361f5e08f9709b9b2&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/SoundPEATS_H3.jpg" },
    "tamron-17-70mm-f28-di-iii-a-vc-rxd-lens-for-sony-e-aps-c-mirrorless-cameras-black": { name: "Tamron 17-70mm f/2.8 Di III-A VC RXD Lens for Sony E APS-C Mirrorless Cameras Black", price: null, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB08PFNNKCC%2Fref%3Dcm_sw_r_as_gl_api_gl_i_EF9Q6PYQCF8VA23QH9WA%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3D513b0674e336d5df2e57e5df060855b7&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/Tamron_17-70mm_f28_Di_III-A_VC_RXD_Lens_for_Sony_E_APS-C_Mirrorless_Cameras_Black.jpg" },
    "tanchjim-fola": { name: "TANCHJIM FOLA", price: 200, url: "https://www.linsoul.com/products/tanchjim-fola?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/TANCHJIM_FOLA.jpg" },
    "tanchjim-soda": { name: "TANCHJIM SODA", price: 310, url: "https://www.linsoul.com/products/tanchjim-soda?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/TANCHJIM_SODA.jpg" },
    "tangzu-tang-sancai": { name: "TANGZU Tang Sancai", price: null, url: "https://www.linsoul.com/products/tangzu-tang-sancai?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/TANGZU_Tang_Sancai.jpg" },
    "tangzu-waner-sg-ii-red-lion": { name: "TANGZU Wan’er S.G II Red Lion", price: 23, url: "https://www.linsoul.com/products/tangzu-wan-er-s-g-ii-bass-version-lion-edition?_pos=1&_sid=d5b86e704&_ss=r&sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/TANGZU_Waner_SG_II_Red_Lion.jpg" },
    "thieaudio-hype-4-mkii": { name: "THIEAUDIO HYPE 4 MKII", price: 400, url: "https://www.linsoul.com/products/thieaudio-hype-4-mkii?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/THIEAUDIO_HYPE_4_MKII.jpg" },
    "tinhifi-p1-max-ii": { name: "TINHIFI P1 MAX II", price: 110, url: "https://shenzhenaudio.com/products/tinhifi-p1-max-ii-giant-panda-14-2mm-planar-in-ear-headphone?ref=tsmeyyjl&utm_source=affiliate", pick: false, image: "images/TINHIFI_P1_MAX_II.jpg" },
    "tinhifi-t6": { name: "TINHIFI T6", price: 105, url: "https://shenzhenaudio.com/products/tinhifi-t6-1dd-1ba-in-ear-headphone?ref=tsmeyyjl&utm_source=affiliate", pick: false, image: "images/TINHIFI_T6.jpg" },
    "topping-dx1-ii": { name: "Topping DX1 II", price: 120, url: "https://apos.audio/products/topping-dx1-ii-gaming-headphone-dac-amp?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/Topping_DX1_II.jpg" },
    "trn-black-pearl": { name: "TRN Black Pearl", price: 37, url: "https://www.linsoul.com/products/trn-black-pearl?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/TRN_Black_Pearl.jpg" },
    "truthear-gate": { name: "Truthear Gate", price: 20, url: "https://shenzhenaudio.com/products/truthear-gate-dynamic-driver-in-ear-headphone?ref=tsmeyyjl&utm_source=affiliate", pick: false, image: "images/Truthear_Gate.png" },
    "xduoo-mh-02": { name: "xDuoo MH-02", price: 130, url: "https://www.linsoul.com/products/xduoo-mh-02?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/xDuoo_MH-02.jpg" },
    "xenns-mangird-tea-pro": { name: "XENNS Mangird Top Pro", price: 500, url: "https://www.linsoul.com/products/xenns-mangird-top-pro?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/XENNS_Mangird_Tea_Pro.jpg" },
    "yanyin-baker": { name: "Yanyin Baker", price: 500, url: "https://www.linsoul.com/products/yanyin-baker?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Yanyin_Baker.jpg" },
    "zen-dac-3": { name: "ZEN DAC 3", price: 230, url: "https://ifi-audio.com/products/zen-dac-3?sca_ref=10519355.D1AXS2sPYkLyQJvS", pick: false, image: "images/ZEN_DAC_3.jpg" },
    "ziigaat-x-fresh-reviews-arete-ii": { name: "ZiiGaat x Fresh Reviews Arete II", price: 280, url: "https://www.linsoul.com/products/ziigaat-x-fresh-reviews-arete-ii?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/ZiiGaat_x_Fresh_Reviews_Arete_II.jpg" },
    "ziigaat-x-hangoutaudio-odyssey-2": { name: "ZiiGaat x Hangout.Audio: Odyssey 2", price: 250, url: "https://www.linsoul.com/products/ziigaat-x-hangout-audio-odyssey-2?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/ZiiGaat_x_HangoutAudio_Odyssey_2.jpg" },
    "ziigaat-x-vivir-digital-rumba": { name: "ZiiGaat x Vivir Digital: RUMBA", price: 35, url: "https://www.linsoul.com/products/ziigaat-x-vivir-digital-rumba?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/ZiiGaat_x_Vivir_Digital_RUMBA.jpg" }
};

// Layout mapping arrays fetching from catalog book rows to minimize page duplication footprint
const gearData = {
    "My Audio Collection / Collabs": [
        "7hz-x-crinacle-zero-2", "fiio-eh11", "kiwi-ears-x-bmedia-chorus", "bmedia-terras-cable",
        "soundpeats-clip1", "apos-x-community-gremlin-tube-amp", "shanling-m0-pro", "but-constantly-on-sale-sennheiser-hd-599",
        "moondrop-x-smsl-dha15", "but-constantly-on-sale-focal-hadenys", "letshuoer-mystic-8", "shanling-m7t",
        "audeze-mm-500", "audeze-lcd-3"
    ],
    "IEMs": [
        "truthear-gate", "tangzu-waner-sg-ii-red-lion", "7hz-x-crinacle-zero-2", "kiwi-ears-belle",
        "nicehck-tears", "ziigaat-x-vivir-digital-rumba", "ooopusx-op22", "kiwi-ears-x-bmedia-chorus",
        "kiwi-ears-cadenza-ii", "kefine-klean", "inawaken-dawn-ms", "apos-x-community-rock-lobster-iems",
        "moondrop-lan-ii", "inawaken-dawn-mistwood", "kefine-delci", "simgot-ew300",
        "juzear-x-z-reviews-defiant", "moondrop-rays", "fosi-audio-im4", "tinhifi-t6",
        "tinhifi-p1-max-ii", "kiwi-ears-tude", "simgot-em6l", "7hz-x-crinacle-divine",
        "basn-bmaster5", "crinear-daybreak", "letshuoer-astralis", "hidizs-mp145-pro",
        "tanchjim-fola", "nicehck-nx8", "ziigaat-x-hangoutaudio-odyssey-2", "nicehck-nx8-se",
        "kiwi-ears-halcyon", "kiwi-ears-septet", "ziigaat-x-fresh-reviews-arete-ii", "kiwi-ears-astral",
        "tanchjim-soda", "punch-audio-martilo", "crinear-reference", "inawaken-twilight-ds",
        "xenns-mangird-tea-pro", "thieaudio-hype-4-mkii", "nicehck-nx8ti-limited-edition", "kiwi-ears-x-hbb-punch",
        "fiio-oak-nano", "yanyin-baker", "xenns-mangird-tea-pro", "letshuoer-ember",
        "letshuoer-mystic-8", "ioaudio-cielo", "fatfreq-maestro-se-universals"
    ],
    "Headphones": [
        "moondrop-old-fashioned", "fiio-jade-audio-jt3", "kiwi-ears-altruva", "simgot-ep5",
        "fiio-jade-audio-jt3", "fiio-ft1", "sony-inzone-h6-air", "headset-drop-pc38x",
        "fiio-ft1-pro", "sennheiser-hd599", "sennheiser-hd-560-s", "hifiman-sundara",
        "rog-x-hifiman-kithara", "harmonicdyne-romantic", "kickstarter-thieaudio-cypher", "sennheiser-hd620s",
        "dunu-mortise", "sivga-peng", "fosi-audio-i5", "focal-azurys",
        "fiio-ft7", "focal-hadenys", "moondrop-skyland", "meze-109-pro",
        "audeze-mm-500", "audeze-lcd-3"
    ],
    "Portable DAC/AMP": [
        "kiwi-ears-ad1", "jcally-jm6-pro", "nicehck-nk1-max", "kiwi-ears-allegro-mini",
        "trn-black-pearl", "bluetooth-hiby-w3-ii", "kiwi-ears-allegro-pro", "moondrop-dawn-pro-2",
        "nicehck-octave", "crinear-protocol-max", "fiio-ka15", "fosi-audio-ds3",
        "fosi-audio-ds3", "moondrop-moonriver-3", "questyle-m15i", "shanling-ua7-its-got-a-tube",
        "questyle-sigma"
    ],
    "Desktop DAC/AMP": [
        "ifi-uno", "topping-dx1-ii", "apos-x-community-gremlin-tube-amp", "xduoo-mh-02",
        "schiit-fulla", "fiio-k11", "fosi-audio-k7", "fosi-audio-zh3",
        "zen-dac-3", "schiit-gunnr-mission-critical", "da-alpha", "moondrop-x-smsl-dha15"
    ],
    "Digital Audio Players": [
        "fiio-snowsky-echo-mini", "hiby-r1", "shanling-m0s", "shanling-m0-pro",
        "hidizs-x-linsoul-ap80-pro-max", "shanling-m1-plus", "hiby-r4", "fiio-m21",
        "hiby-r6-iii", "shanling-m1-plus", "cayin-n3ultra", "fiio-m23",
        "shanling-m7t"
    ],
    "Wireless Earbuds": [
        "moondrop-space-travel-2", "moondrop-pudding", "cmf-buds-pro-2", "soundpeats-clip1-open-ear-earbuds",
        "moondrop-golden-ages-2", "moondrop-robin", "soundpeats-h3", "soundpeats-air5-pro"
    ],
    "Wireless Headphones": [
        "fiio-eh11", "1mii-y8", "fiio-eh13", "moondrop-edge",
        "cmf-by-nothing-headphone-pro", "nothing-headphone-a", "edifier-wh950nb-gen-2", "gaming-audeze-maxwell-2",
        "bose-qc-ultra-2", "sennheiser-hdb-630"
    ],
    "IEM Cables & Eartips": [
        "nicehck-c04-liquid-silicone-eartips", "tangzu-tang-sancai", "nicehck-08-silicone-ear-tips-noise-isolating", "mic-moondrop-mc1",
        "nicehck-blackwheat-iem-wmic", "letshuoer-lc01-usb-type-c", "original-kiwi-ears-terras", "kiwi-ears-x-bmedia-terras"
    ],
    "Headphone Accessories": [
        "salad-halo-headphone-stand", "hart-audio"
    ],
    "Tech I Use": [
        "dji-osmo-pocket-3-creator-combo", "keychron-m6-8k-wireless-gaming-mouse", "keychron-q1-ultra-8k-75-wireless-mechanical-keyboard", "sennheiser-mke-400-mobile-kit",
        "anker-555-usb-c-hub-8-in-1", "anker-140w-max-4-port-gan-usb-c-charger", "kf-concept-60-inch-carbon-fiber-camera-tripodsuper-lightweight-compact-travel-tripod-with-360-degree-ball-headquick-release-platedetachable-monopod-17-lb-load-capacity-for-slr-dslr-c225c0-ba225", "kf-concept-67mm-variable-fader-nd2-32-nd-filter-and-cpl-circular-polarizing-lens-filter-in-1-for-camera-lens-waterproof-neutral-density-polarizer-filter-nano-d-series",
        "tamron-17-70mm-f28-di-iii-a-vc-rxd-lens-for-sony-e-aps-c-mirrorless-cameras-black", "sony-alpha-a6400-mirrorless-camera-compact-aps-c-interchangeable-lens-digital-camera-with-real-time-eye-auto-focus-4k-video-flip-up-touchscreen-e-mount-compatible-cameras-ilce-6400b-body"
    ]
};