const gearData = {
    "IEMs": [
        { name: "Truthear Gate", price: 20, url: "https://amzn.to/3UzzHSQ", pick: false, image: "images/Truthear_Gate.png" },
        { name: "7hz x Crinacle Zero 2", price: 25, url: "https://www.linsoul.com/products/7hz-x-crinacle-zero-2?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/7hz_x_Crinacle_Zero_2.png" },
        { name: "Kiwi Ears Belle", price: 30, url: "https://www.linsoul.com/products/kiwi-ears-belle?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/Kiwi_Ears_Belle.jpg" },
        { name: "LETSHUOER D02", price: 30, url: "https://letshuoer.net/products/letshuoer-d02?sca_ref=9494666.Bbv8z0WcOh", pick: false, image: "images/LETSHUOER_D02.jpg" },
        { name: "Kiwi Ears Cadenza", price: 35, url: "https://www.linsoul.com/products/kiwi-ears-cadenza?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_Cadenza.jpg" },
        { name: "Kefine Klean", price: 50, url: "https://www.linsoul.com/products/kefine-klean?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/Kefine_Klean.png" },
        { name: "INAWAKEN DAWN Ms", price: 50, url: "https://www.linsoul.com/products/inawaken-dawn-ms?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/INAWAKEN_DAWN_Ms.jpg" },
        { name: "Apos x Community Rock Lobster IEMs", price: 60, url: "https://apos.audio/products/apos-x-community-rock-lobster-iems?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/Apos_x_Community_Rock_Lobster_IEMs.jpg" },
        { name: "Moondrop LAN II", price: 60, url: "https://www.linsoul.com/products/moondrop-lanii?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Moondrop_LAN_II.jpg" },
        { name: "Truthear x Crinacle Zero Blue 2", price: 70, url: "https://amzn.to/45lfczx", pick: false, image: "images/Truthear_x_Crinacle_Zero_Blue_2.png" },
        { name: "Kefine Delci", price: 75, url: "https://www.linsoul.com/products/kefine-delci?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kefine_Delci.jpg" },
        { name: "Dunu Titan S2", price: 80, url: "https://www.linsoul.com/products/dunu-titan-s2?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Dunu_Titan_S2.png" },
        { name: "SIMGOT EW300", price: 80, url: "https://www.linsoul.com/products/simgot-ew300?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/SIMGOT_EW300.jpg" },
        { name: "MOONDROP RAYS", price: 100, url: "https://www.linsoul.com/products/moondrop-rays?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/MOONDROP_RAYS.jpg" },
        { name: "Moondrop Aria 2", price: 100, url: "https://www.linsoul.com/products/moondrop-aria2?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Moondrop_Aria_2.png" },
        { name: "Save 10%   Fosi Audio IM4", price: null, url: "https://fosiaudioshop.com/products/fosi-audio-im4?sca_ref=9795660.evSmNtMEvd&utm_source=affiliate&utm_medium=referral&utm_campaign=uppromote", pick: true, image: "images/Save_10___Fosi_Audio_IM4.jpg" },
        { name: "Kiwi Ears Étude", price: 120, url: "https://www.linsoul.com/products/kiwi-ears-etude?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_Étude.jpg" },
        { name: "SIMGOT EM6L", price: 125, url: "https://www.linsoul.com/products/simgot-em6l?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/SIMGOT_EM6L.jpg" },
        { name: "7Hz x Crinacle: Divine", price: 150, url: "https://www.linsoul.com/products/7hz-x-crinacle-divine?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/7Hz_x_Crinacle_Divine.jpg" },
        { name: "7Hz x Crinacle: Diablo", price: 150, url: "https://www.linsoul.com/products/7hz-x-crinacle-diablo?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/7Hz_x_Crinacle_Diablo.jpg" },
        { name: "Crinear Daybreak", price: 170, url: "https://www.linsoul.com/products/crinear-daybreak?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Crinear_Daybreak.jpg" },
        { name: "LETSHUOER S12 Ultra", price: 170, url: "https://letshuoer.net/products/letshuoer-s12-ultra?sca_ref=9494666.Bbv8z0WcOh", pick: false, image: "images/LETSHUOER_S12_Ultra.jpg" },
        { name: "NICEHCK NX8", price: 200, url: "https://nicehck.com/products/nicehck-nx8-in-ear-monitor-with-1dd-6ba-1pzt-8-unit-hybrid-earphone?sca_ref=9185017.bnGYqsxONg", pick: false, image: "images/NICEHCK_NX8.png" },
        { name: "7HZ Timeless II", price: 230, url: "https://www.linsoul.com/products/7hz-timeless-ii?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/7HZ_Timeless_II.jpg" },
        { name: "ZiiGaat x Hangout.Audio: Odyssey 2", price: 250, url: "https://www.linsoul.com/products/ziigaat-x-hangout-audio-odyssey-2?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/ZiiGaat_x_HangoutAudio_Odyssey_2.jpg" },
        { name: "NICEHCK NX8 SE", price: 250, url: "https://nicehck.com/products/nicehck-nx8-se-nx8-special-edition-iems?sca_ref=9185017.bnGYqsxONg", pick: true, image: "images/NICEHCK_NX8_SE.jpg" },
        { name: "Kiwi Ears Septet", price: 270, url: "https://www.linsoul.com/products/kiwi-ears-septet?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_Septet.jpg" },
        { name: "Kiwi Ears Astral", price: 300, url: "https://www.linsoul.com/products/kiwi-ears-astral?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_Astral.jpg" },
        { name: "Punch Audio Martilo", price: 330, url: "https://www.linsoul.com/products/punch-audio-martilo?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Punch_Audio_Martilo.png" },
        { name: "ZiiGaat Horizon", price: 330, url: "https://www.linsoul.com/products/ziigaat-horizon?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/ZiiGaat_Horizon.jpg" },
        { name: "INAWAKEN Twilight-DS", price: 350, url: "https://www.linsoul.com/products/inawaken-twilight-ds?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/INAWAKEN_Twilight-DS.jpg" },
        { name: "XENNS Mangird Tea Pro", price: 360, url: "https://www.linsoul.com/products/xenns-mangird-tea-pro?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/XENNS_Mangird_Tea_Pro.jpg" },
        { name: "Kiwi Ears x HBB Punch", price: 450, url: "https://www.linsoul.com/products/kiwi-ears-x-hbb-punch?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_x_HBB_Punch.jpg" },
        { name: "XENNS Mangird Top Pro", price: 500, url: "https://www.linsoul.com/products/xenns-mangird-top-pro?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/XENNS_Mangird_Top_Pro.jpg" },
        { name: "THIEAUDIO Oracle MKIII", price: 590, url: "https://www.linsoul.com/products/thieaudio-oracle-mkiii?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/THIEAUDIO_Oracle_MKIII.jpg" },
        { name: "LETSHUOER Mystic 8", price: 990, url: "https://letshuoer.net/products/letshuoer-mystic-8-wired-iem-hifi-earphones-8-ba-drivers-in-ear-monitor?sca_ref=9494666.Bbv8z0WcOh", pick: false, image: "images/LETSHUOER_Mystic_8.jpg" }
    ],
    "Headphones": [
        { name: "MOONDROP Old Fashioned", price: 25, url: "https://www.linsoul.com/products/moondrop-old-fashioned?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/MOONDROP_Old_Fashioned.jpg" },
        { name: "Kiwi Ears Altruva", price: 70, url: "https://www.linsoul.com/products/kiwi-ears-altruva?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_Altruva.jpg" },
        { name: "Simgot EP5", price: 98, url: "https://www.linsoul.com/products/simgot-ep5?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Simgot_EP5.png" },
        { name: "FiiO JadeAudio JT7", price: 120, url: "https://apos.audio/products/fiio-jadeaudio-jt7-open-back-planar-headphones?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/FiiO_JadeAudio_JT7.jpg" },
        { name: "FiiO FT1", price: 160, url: "https://www.linsoul.com/products/fiio-ft1?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/FiiO_FT1.png" },
        { name: "Gaming Headset DROP PC38X", price: 200, url: "https://amzn.to/3HhZLiJ", pick: false, image: "images/Gaming_Headset_DROP_PC38X.png" },
        { name: "Sennheiser HD599", price: 200, url: "https://amzn.to/4nl2vvE", pick: true, image: "images/Sennheiser_HD599.png" },
        { name: "Sennheiser HD 560 S", price: 275, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB08J9MVB6W%2Fref%3Dcm_sw_r_as_gl_api_gl_i_GHA0516AARS5E63DD09E%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3Dcb1741c88340e67df6d3d142d6253491&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/Sennheiser_HD_560_S.jpg" },
        { name: "Hifiman Sundara", price: 280, url: "https://apos.audio/products/hifiman-sundara-planar-magnetic-headphones?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/Hifiman_Sundara.png" },
        { name: "Sennheiser HD620S", price: 400, url: "https://amzn.to/4eytz6T", pick: false, image: "images/Sennheiser_HD620S.png" },
        { name: "Meze 105 AER", price: 400, url: "https://mezeaudio.com/products/105-aer?_ef_transaction_id=&oid=46&affid=287.", pick: false, image: "images/Meze_105_AER.png" },
        { name: "SIVGA Peng", price: 500, url: "https://www.linsoul.com/products/sivga-peng?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/SIVGA_Peng.jpg" },
        { name: "Fosi Audio i5", price: 550, url: "https://fosiaudioshop.com/products/i5-headphones?sca_ref=9795660.evSmNtMEvd&utm_source=affiliate&utm_medium=referral&utm_campaign=uppromote", pick: true, image: "images/Fosi_Audio_i5.jpg" },
        { name: "Focal Azurys", price: 600, url: "https://amzn.to/4evNOSA", pick: false, image: "images/Focal_Azurys.png" },
        { name: "Focal Hadenys", price: 750, url: "https://amzn.to/4oxjjj6", pick: true, image: "images/Focal_Hadenys.png" },
        { name: "Meze 109 Pro", price: 800, url: "https://apos.audio/products/meze-audio-109-pro?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/Meze_109_Pro.png" }
    ],
    "Portable DAC/AMP": [
        { name: "JCALLY JM12", price: 10, url: "https://amzn.to/4eB4gRv", pick: false, image: "images/JCALLY_JM12.png" },
        { name: "JCALLY JM6 Pro", price: 18, url: "https://amzn.to/3TMeGUZ", pick: false, image: "images/JCALLY_JM6_Pro.png" },
        { name: "NICEHCK NK1 MAX", price: 24, url: "https://nicehck.com/products/nicehck-nki-max-portable-dac-adapter-cable?sca_ref=9185017.bnGYqsxONg", pick: true, image: "images/NICEHCK_NK1_MAX.jpg" },
        { name: "Kiwi Ears Allegro Mini", price: 25, url: "https://www.linsoul.com/products/kiwi-ears-allegro-mini?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_Allegro_Mini.jpg" },
        { name: "TRN Black Pearl", price: 37, url: "https://www.linsoul.com/products/trn-black-pearl?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/TRN_Black_Pearl.jpg" },
        { name: "Bluetooth HiBy W3 II", price: 49, url: "https://www.linsoul.com/products/hiby-w3-ii?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Bluetooth_HiBy_W3_II.png" },
        { name: "Kiwi Ears Allegro Pro", price: 60, url: "https://www.linsoul.com/products/kiwi-ears-allegro-pro?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Kiwi_Ears_Allegro_Pro.jpg" },
        { name: "Moondrop Dawn Pro 2", price: 60, url: "https://www.linsoul.com/products/moondrop-dawn-pro2?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Moondrop_Dawn_Pro_2.jpg" },
        { name: "FiiO KA13", price: 80, url: "https://www.linsoul.com/products/fiio-ka13?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/FiiO_KA13.jpg" },
        { name: "CrinEar Protocol Max", price: 90, url: "https://www.linsoul.com/products/crinear-protocol-max?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/CrinEar_Protocol_Max.jpg" },
        { name: "FiiO KA15", price: 95, url: "https://www.linsoul.com/products/fiio-ka15?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/FiiO_KA15.png" },
        { name: "Fosi Audio DS3", price: 100, url: "https://fosiaudioshop.com/products/fosi-audio-ds3?sca_ref=9795660.evSmNtMEvd&utm_source=affiliate&utm_medium=referral&utm_campaign=uppromote", pick: false, image: "images/Fosi_Audio_DS3.jpg" },
        { name: "Questyle M15i", price: 250, url: "https://amzn.to/4evROCA", pick: false, image: "images/Questyle_M15i.png" },
        { name: "Shanling UA7 ITS GOT A TUBE", price: 270, url: "https://www.linsoul.com/products/shanling-ua7?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/Shanling_UA7_ITS_GOT_A_TUBE.jpg" }
    ],
    "Desktop DAC/AMP": [
        { name: "IFI Uno", price: 79, url: "https://apos.audio/products/ifi-uno?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/IFI_Uno.png" },
        { name: "Topping DX1 Mini", price: 99, url: "https://apos.audio/products/topping-dx1-dac-amp?sca_ref=9857353.lTWqXMxzNa", pick: true, image: "images/Topping_DX1_Mini.png" },
        { name: "xDuoo MH-02", price: 130, url: "https://www.linsoul.com/products/xduoo-mh-02?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/xDuoo_MH-02.jpg" },
        { name: "Schiit Fulla", price: 136, url: "https://amzn.to/403r0nk", pick: false, image: "images/Schiit_Fulla.png" },
        { name: "FiiO K11", price: 140, url: "https://www.linsoul.com/products/fiio-k11?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/FiiO_K11.jpg" },
        { name: "Fosi Audio K7", price: 200, url: "https://fosiaudioshop.com/products/k7-dac-headphone-amp?sca_ref=9795660.evSmNtMEvd&utm_source=affiliate&utm_medium=referral&utm_campaign=uppromote", pick: false, image: "images/Fosi_Audio_K7.jpg" },
        { name: "Fosi Audio ZH3", price: 200, url: "https://fosiaudioshop.com/products/zh3-dac-headphone-amp-preamp?sca_ref=9795660.evSmNtMEvd&utm_source=affiliate&utm_medium=referral&utm_campaign=uppromote", pick: true, image: "images/Fosi_Audio_ZH3.jpg" },
        { name: "Schiit Gunnr Mission-Critical", price: 259, url: "https://amzn.to/3TsPAKC", pick: false, image: "images/Schiit_Gunnr_Mission-Critical.png" }
    ],
    "Digital Audio Players": [
        { name: "HiBy R1", price: 85, url: "https://www.linsoul.com/products/hiby-r1?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/HiBy_R1.jpg" },
        { name: "Hidiz x Linsoul AP80 PRO MAX", price: 190, url: "https://www.linsoul.com/products/hidizs-x-linsoul-ap80pro-max?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Hidiz_x_Linsoul_AP80_PRO_MAX.jpg" },
        { name: "Shanling M1 Plus", price: 210, url: "https://www.linsoul.com/products/shanling-m1-plus?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Shanling_M1_Plus.jpg" },
        { name: "HiBy R4", price: 250, url: "https://www.linsoul.com/products/hiby-r4?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/HiBy_R4.jpg" },
        { name: "FiiO M21", price: 330, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0F8HVKTB9%2Fref%3Dcm_sw_r_as_gl_api_gl_i_3AE8XXTMSQ46W1HFYXMR%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3Dabcb6e8f945a52f32b302ca17fd8eb8c&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/FiiO_M21.jpg" },
        { name: "Hiby R6 III", price: 440, url: "https://www.linsoul.com/products/hiby-r6-iii-2025?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Hiby_R6_III.jpg" },
        { name: "Shanling M3 Plus", price: 469, url: "https://www.linsoul.com/products/shanling-m3-plus?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Shanling_M3_Plus.jpg" },
        { name: "FiiO M23", price: 720, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0D14PGZV1%2Fref%3Dcm_sw_r_as_gl_api_gl_i_TK9CDFZVGYHMD8H3WVQX%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3D98aa5a3055150f1c4be2bcfc78367188&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/FiiO_M23.jpg" }
    ],
    "Wireless Earbuds": [
        { name: "Moondrop Space Travel 2", price: 30, url: "https://www.linsoul.com/products/moondrop-space-travel-2?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/Moondrop_Space_Travel_2.jpg" },
        { name: "TANCHJIM MINO", price: 42, url: "https://www.linsoul.com/products/tanchjim-mino?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/TANCHJIM_MINO.jpg" },
        { name: "CMF Buds Pro 2", price: 60, url: "https://amzn.to/45m8kku", pick: false, image: "images/CMF_Buds_Pro_2.png" },
        { name: "Moondrop Golden Ages 2", price: 90, url: "https://amzn.to/46e5hMZ", pick: false, image: "images/Moondrop_Golden_Ages_2.png" },
        { name: "Moondrop Robin", price: 120, url: "https://amzn.to/4mslt22", pick: true, image: "images/Moondrop_Robin.png" },
        { name: "SoundPEATS H3", price: 130, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0FJKYVSMP%2Fref%3Dcm_sw_r_as_gl_api_gl_i_RXTZ92A5JQYJFTP9PNMW%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3D60a065112fb14a8361f5e08f9709b9b2&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/SoundPEATS_H3.jpg" },
        { name: "Soundpeats Air5 Pro+", price: 170, url: "https://soundpeats.com/collections/new-arrivals/products/air5-pro-plus-eu", pick: false, image: "images/Soundpeats_Air5_Pro.jpg" }
    ],
    "Wireless Headphones": [
        { name: "1Mii Y8+", price: 60, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0DZHNWPKD%2Fref%3Dcm_sw_r_as_gl_api_gl_i_8N6015E1PEBPS034B4P8%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3D8803c8bc5823c050876f4707611b1a71&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/1Mii_Y8.jpg" },
        { name: "Moondrop Edge", price: 90, url: "https://www.linsoul.com/products/moondrop-edge?_pos=10&_sid=2605a58ec&_ss=r&sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/Moondrop_Edge.jpg" },
        { name: "CMF by Nothing Headphone Pro", price: 100, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0FKG6TDRR%2Fref%3Dcm_sw_r_as_gl_api_gl_i_10TV6G03W2PC25HEMKE4%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3D8cc5f836f5310ef8f0690b0d272abf92&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/CMF_by_Nothing_Headphone_Pro.jpg" },
        { name: "Edifier WH950NB Gen 2", price: 200, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0F9DR3ZPG%2Fref%3Dcm_sw_r_as_gl_api_gl_i_GB8KPT5H212NJDBAW7FR%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3Dea64e230ceca064790cccc11d02a9ecb&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/Edifier_WH950NB_Gen_2.jpg" },
        { name: "Wireless Gaming Headset Audeze Maxwell", price: 330, url: "https://apos.audio/products/audeze-maxwell-wireless-gaming-headset?sca_ref=9857353.lTWqXMxzNa", pick: false, image: "images/Wireless_Gaming_Headset_Audeze_Maxwell.png" },
        { name: "Bose QC Ultra 2", price: 450, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0FDKQ2FG6%2Fref%3Dcm_sw_r_as_gl_api_gl_i_KMZZ1JFZZ6GY3C88QWTP%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3D09ba8bbe979351a9c6fb08316894060e&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/Bose_QC_Ultra_2.jpg" },
        { name: "Sennheiser HDB 630", price: 500, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0FK4K5Z37%2Fref%3Dcm_sw_r_as_gl_api_gl_i_J5QCFF41K3X5F978M3Z1%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3Ddc35d45f37440632ee3611e6c7b1fbdd&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/Sennheiser_HDB_630.jpg" }
    ],
    "IEM Cables & Eartips": [
        { name: "NICEHCK C04 Liquid Silicone Eartips", price: null, url: "https://nicehck.com/products/nicehck-c04-liquid-silicone-ear-tips?sca_ref=9185017.bnGYqsxONg", pick: true, image: "images/NICEHCK_C04_Liquid_Silicone_Eartips.jpg" },
        { name: "TANGZU Tang Sancai", price: null, url: "https://www.linsoul.com/products/tangzu-tang-sancai?sca_ref=8292414.EuVtu9PPWr", pick: false, image: "images/TANGZU_Tang_Sancai.jpg" },
        { name: "NICEHCK 08 Silicone Ear Tips Noise Isolating", price: null, url: "https://nicehck.com/products/nicehck-08-silicone-ear-tips-noise-isolating-earbuds-cushion-earphone-accessories-improve-clear-vocal-for-nx7mk4-zero-2-t2-gk20?sca_ref=9185017.bnGYqsxONg", pick: false, image: "images/NICEHCK_08_Silicone_Ear_Tips_Noise_Isolating.jpg" },
        { name: "NICEHCK C16-4 16 Core Silver Plated Cable", price: null, url: "https://nicehck.com/products/nicehck-c16-4-16-core-silver-plated-cable?sca_ref=9185017.bnGYqsxONg", pick: false, image: "images/NICEHCK_C16-4_16_Core_Silver_Plated_Cable.jpg" },
        { name: "NICEHCK BlackWheat IEM w/mic", price: null, url: "https://nicehck.com/products/nicehck-blackwheat-8-core-silver-plated-copper-microphone-cable-mmcx-qdc-0-78-2pin-for-db3-zsn-zst-as10-zs10-edx-c10-ca4-c12?variant=47860952662307&sca_ref=9185017.bnGYqsxONg", pick: false, image: "images/NICEHCK_BlackWheat_IEM_wmic.jpg" },
        { name: "LETSHUOER LC01 USB Type-C", price: null, url: "https://letshuoer.net/products/letshuoer-lc01-usb-type-c-earphones-cable?sca_ref=9494666.Bbv8z0WcOh", pick: false, image: "images/LETSHUOER_LC01_USB_Type-C.jpg" },
        { name: "Kiwi Ears Terras", price: null, url: "https://www.linsoul.com/products/kiwi-ears-terras?sca_ref=8292414.EuVtu9PPWr", pick: true, image: "images/Kiwi_Ears_Terras.jpg" }
    ],
    "Cables & Interconnects by Hart Audio": [
        { name: "Hart Audio", price: null, url: "https://hartaudiocables.com/?srsltid=AfmBOorgjh48BSZb8D_oMEq1M8iBLxZtShzNSawmyPz1jcFDVez2CGKQ", pick: false, image: "images/Hart_Audio.jpg" }
    ],
    "Tech I Use": [
        { name: "K&F Concept 60 inch Carbon Fiber Camera Tripod,Super Lightweight Compact Travel Tripod with 360 Degree Ball Head,Quick Release Plate,Detachable Monopod 17 lb Load Capacity for SLR DSLR C225C0 (BA225)", price: null, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB081DYTR9J%2Fref%3Dcm_sw_r_as_gl_api_gl_i_8M5S06Y5VWKNQEJ8C92X%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3Dd987bf5298e45df9bfdb78f767025db2&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/KF_Concept_60_inch_Carbon_Fiber_Camera_TripodSuper_Lightweight_Compact_Travel_Tripod_with_360_Degree_Ball_HeadQuick_Release_PlateDetachable_Monopod_17_lb_Load_Capacity_for_SLR_DSLR_C225C0_BA225.jpg" },
        { name: "K&F CONCEPT 67mm Variable Fader ND2-32 ND Filter and CPL Circular Polarizing Lens Filter in 1 for Camera Lens Waterproof Neutral Density Polarizer Filter (Nano-D Series)", price: null, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0CNV9W4V4%2Fref%3Dcm_sw_r_as_gl_api_gl_i_dl_BAV07S149SNKBK84W03Z%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3D7c705aee77f7273683cd5d0d4d8feadb&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/KF_CONCEPT_67mm_Variable_Fader_ND2-32_ND_Filter_and_CPL_Circular_Polarizing_Lens_Filter_in_1_for_Camera_Lens_Waterproof_Neutral_Density_Polarizer_Filter_Nano-D_Series.jpg" },
        { name: "Tamron 17-70mm f/2.8 Di III-A VC RXD Lens for Sony E APS-C Mirrorless Cameras Black", price: null, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB08PFNNKCC%2Fref%3Dcm_sw_r_as_gl_api_gl_i_EF9Q6PYQCF8VA23QH9WA%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3D513b0674e336d5df2e57e5df060855b7&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/Tamron_17-70mm_f28_Di_III-A_VC_RXD_Lens_for_Sony_E_APS-C_Mirrorless_Cameras_Black.jpg" },
        { name: "Sony Alpha a6400 Mirrorless Camera: Compact APS-C Interchangeable Lens Digital Camera with Real-Time Eye Auto Focus, 4K Video & Flip Up Touchscreen - E Mount Compatible Cameras - ILCE-6400/B Body", price: null, url: "https://r.amzlink.to/?btn_url=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB07MTWVN3M%2Fref%3Dcm_sw_r_as_gl_api_gl_i_FNG9TMGEJ2YYAD1EY767%3FlinkCode%3Dml1%26tag%3Dbmedia091-20%26linkId%3D226d9c09123e826a0039edad56cfc99c&btn_ref=org-433bb393e1b8b503", pick: false, image: "images/Sony_Alpha_a6400_Mirrorless_Camera_Compact_APS-C_Interchangeable_Lens_Digital_Camera_with_Real-Time_Eye_Auto_Focus_4K_Video__Flip_Up_Touchscreen_-_E_Mount_Compatible_Cameras_-_ILCE-6400B_Body.jpg" }
    ]
};